// 문제1 사용자 주문 js
let name = prompt("이름을 입력해주세요.")
let drink = prompt("원하는 음료를 입력해주세요.")
let int = prompt("주문수량을 입력해주세요.")
console.log("[주문 접수]")
console.log("이름")
console.log(name)
console.log("메뉴")
console.log(drink)
console.log("수량")
console.log(int)
// 문제2 사용자 운동기록 js
let Name = prompt("이름을 입력해주세요.")
let menu = prompt("오늘 하신 운동 종류를 입력해주세요.")
let time = prompt("운동 시간(분)을 입력해주세요.")
let kcal = time * 7
console.log("[운동 기록]")
console.log("이름")
console.log(Name)
console.log("운동종류")
console.log(menu)
console.log("운동시간")
console.log(time)
console.log("칼로리")
console.log(kcal)
